### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by niker** [WasinUddy/Montainer#12]
Hi, the app works fine but is there a way to automate starting the internal mc server after a machine reboot or container restart?

**Comment by WasinUddy** [comment]
Hi! Thanks for using Montainer. I've added functionality to automate starting the internal Minecraft server on container restart. You can check out the updated release here: [GitHub](https://github.com/WasinUddy/Montainer/releases/tag/2.0.1).

If you have any more suggestions, feel free to create an issue. And if you enjoy using Montainer, don’t forget to give it a ⭐!

**Comment by niker** [comment]
Perfect, thanks I'll test it once the kids disconnect. Here's your ⭐ :)

I just wish there was a way to export chat messages in the web console, would it be possible to sniff with some network proxy or memory injection on the binary?
