### ISSUE TITLE
Integrate chat logging into the project

### ISSUE THREAD

**Issue by niker** [WasinUddy/Montainer#13]
Hi, I was battling with the inability to monitor chat logs on bedrock servers for long enough, the number of kids on my server is increasing as is the danger of predatory players joining uninvited or cyber-bullying among peers.

So in order to protect my daughters I made it work myself.

It would be great if you could review my little project and (if there is interest) integrate it into Montainer.

It should be possible to pipe the output and intermingle it with the server console. You also get logging to rolling files in a nice readable way.

The default settings will create a resilient daemon that can run side by side with Minecraft and will reconnect if there is a problem or a reboot.

There is one minor annoyance as stated in readme, which may be handled on your side by a console command to minecraft.

Let me know if you're interested or if you have any suggestions that would make your work easier.

https://github.com/niker/mc-bedrock-chatlog

**Comment by WasinUddy** [comment]
The Minecraft bedrock it self already censored a lot of vocab in the chat may i ask what kind of message are you aiming for

**Comment by niker** [comment]
I want to see all player chat and who killed who as it is in Minecraft Java Edition, now with my chat bot that is possible to do.

**Comment by niker** [comment]
Update 1.0.3 allows the chatbot to run in a docker container. I am using it in docker, connecting to a Montainer instance no problem.

**Comment by WasinUddy** [comment]
Glad to hear that. We understand the important to monitored player activity and will find a way to integrate it in the future!!
